version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: boredgame_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: boredgame_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
#  cerbos:
#    image: ghcr.io/cerbos/cerbos:0.38.1
#    environment:
#      CERBOS_NO_TELEMETRY: 1
#    ports:
#      - '3592:3592'
#    volumes:
#      - ./policies:/policies
volumes:
  postgres_data:
  redis_data:
#  policies_data:
  # caddy_data:
  # caddy_config: